version: "3.9"
services:
  db:
    image: postgres:17
    container_name: portfolio_db
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    container_name: portfolio_storage

    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_DEFAULT_BUCKETS: portfolio-storage-bucket
      MINIO_SERVER_URL: https://storage.thiagoodev.com.br
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - storage_data:/data
    entrypoint: >
      sh -c '
        minio server /data --console-address ":9001" &
        sleep 10
        mc alias set myminio http://127.0.0.1:9000 "$MINIO_ROOT_USER" "$MINIO_ROOT_PASSWORD"
        mc anonymous set download myminio/portfolio-storage-bucket
        wait $$!
      '

  app:
    build: .
    container_name: portfolio

    environment:
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_USERNAME: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      GITHUB_URI: ${GITHUB_URI}
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_DEFAULT_BUCKETS: portfolio-storage-bucket
    ports:
      - "8080:8080"
    depends_on:
      - db
      - minio

volumes:
  db_data:
  storage_data:
