version: "3.9"
services:
  db:
    image: postgres:17
    container_name: portfolio_db
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  storage:
    image: nginx:alpine
    container_name: storage_nginx
    ports:
      - "8081:80"
    volumes:
      - storage_data:/usr/share/nginx/html

  app:
    build: .
    container_name: portfolio

    environment:
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_USERNAME: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      GITHUB_URI: ${GITHUB_URI}
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  db_data:
  storage_data:
