version: "3.9"
services:
  db:
    image: postgres:17
    container_name: portfolio_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: portfolio
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: portfolio

    environment:
      DATABASE_URL: jdbc:postgresql://db:5432/portfolio
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      GITHUB_URI: https://api.github.com/users/cthiagoodev/repos
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  db_data:
