ALTER TABLE projects
    ALTER COLUMN name TYPE VARCHAR(100),
    ALTER COLUMN full_name TYPE VARCHAR(200),
    ALTER COLUMN html_url TYPE VARCHAR(500),
    ALTER COLUMN description TYPE VARCHAR(1000),
    ALTER COLUMN language TYPE VARCHAR(50),
    ALTER COLUMN homepage TYPE VARCHAR(500);