// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/cthiagoodev/thiagoodev-portfolio/services/projects_sync/internal/infrastructure/github"
	mock "github.com/stretchr/testify/mock"
)

// NewMockGithubService creates a new instance of MockGithubService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGithubService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGithubService {
	mock := &MockGithubService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockGithubService is an autogenerated mock type for the GithubService type
type MockGithubService struct {
	mock.Mock
}

type MockGithubService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGithubService) EXPECT() *MockGithubService_Expecter {
	return &MockGithubService_Expecter{mock: &_m.Mock}
}

// FetchRepositories provides a mock function for the type MockGithubService
func (_mock *MockGithubService) FetchRepositories(ctx context.Context) ([]github.Project, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for FetchRepositories")
	}

	var r0 []github.Project
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]github.Project, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []github.Project); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]github.Project)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGithubService_FetchRepositories_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchRepositories'
type MockGithubService_FetchRepositories_Call struct {
	*mock.Call
}

// FetchRepositories is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockGithubService_Expecter) FetchRepositories(ctx any) *MockGithubService_FetchRepositories_Call {
	return &MockGithubService_FetchRepositories_Call{Call: _e.mock.On("FetchRepositories", ctx)}
}

func (_c *MockGithubService_FetchRepositories_Call) Run(run func(ctx context.Context)) *MockGithubService_FetchRepositories_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockGithubService_FetchRepositories_Call) Return(projects []github.Project, err error) *MockGithubService_FetchRepositories_Call {
	_c.Call.Return(projects, err)
	return _c
}

func (_c *MockGithubService_FetchRepositories_Call) RunAndReturn(run func(ctx context.Context) ([]github.Project, error)) *MockGithubService_FetchRepositories_Call {
	_c.Call.Return(run)
	return _c
}
