name: Deploy Portfolio

on:
  push:
    branches:
      - main

permissions:
  contents: read

concurrency:
  group: portfolio-deploy
  cancel-in-progress: true

jobs:
  deploy:
    name: Build and Deploy
    runs-on: self-hosted
    environment: production

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Java 25
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}

      - name: Build Application
        run: ./gradlew clean build -x test

      - name: Deploy with Docker Compose
        env:
          DATABASE_URL: ${{ secrets.APP_DB_URL }}
          DATABASE_USER: ${{ secrets.DB_USER }}
          DATABASE_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DATABASE_NAME: ${{ secrets.DB_NAME }}
          GITHUB_URI: ${{ secrets.REPOS_TOKEN_URI }}
          MINIO_ROOT_USER: ${{ secrets.MINIO_ROOT_USER }}
          MINIO_ROOT_PASSWORD: ${{ secrets.MINIO_ROOT_PASSWORD }}
        run: |
          echo "🧩 Deploying with Docker Compose..."
          docker-compose -f docker-compose.prod.yml down --remove-orphans || true        
          docker system prune -af || true
          docker-compose -f docker-compose.prod.yml build --no-cache
          docker-compose -f docker-compose.prod.yml up -d
      - name: Verify Deployment
        run: |
          echo "✅ Checking if container is running..."
          docker ps --filter "name=portfolio" --format "table {{.Names}}\t{{.Status}}"
